create table
  public.transactions (
    transaction_id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    description text null,
    constraint transactions_pkey primary key (transaction_id)
  ) tablespace pg_default;

create table
  public.inventory_ledger (
    id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    gold integer not null default 0,
    red_ml integer not null default 0,
    green_ml integer not null default 0,
    blue_ml integer not null default 0,
    dark_ml integer not null default 0,
    transaction_id bigint null,
    constraint inventory_ledger_pkey primary key (id),
    constraint inventory_ledger_transaction_id_fkey foreign key (transaction_id) references transactions (transaction_id)
  ) tablespace pg_default;

create table
  public.potion_inventory (
    potion_id bigint generated by default as identity,
    sku text not null,
    type integer[] not null,
    cost integer not null,
    name text not null,
    constraint V3_global_inventory_pkey primary key (potion_id),
    constraint potion_inventory_name_key unique (name),
    constraint potion_inventory_potion_id_key unique (potion_id),
    constraint potion_inventory_sku_key unique (sku),
    constraint potion_inventory_type_key unique (
      type
    )
  ) tablespace pg_default;

create table
  public.potion_ledger (
    id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    potion_id bigint null,
    potion_change integer null,
    transaction_id bigint null,
    constraint ledger_pkey primary key (id),
    constraint potion_ledger_potion_id_fkey foreign key (potion_id) references potion_inventory (potion_id),
    constraint potion_ledger_transaction_id_fkey foreign key (transaction_id) references transactions (transaction_id)
  ) tablespace pg_default;

create table
  public.carts (
    cart_id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    name text null,
    constraint carts_pkey primary key (cart_id),
    constraint carts_cart_id_key unique (cart_id)
  ) tablespace pg_default;

create table
  public.cart_items (
    cart_id bigint generated by default as identity,
    potion_id bigint not null,
    quantity integer not null,
    sku text not null,
    constraint cart_items_pkey primary key (cart_id, potion_id)
  ) tablespace pg_default;

